swagger: '2.0'
info:
  version: '1.0.0'
  title: 'Sample API'
  description: Buy or rent spacecrafts

consumes:
  - application/json
produces:
  - application/json

paths:
  /spacecrafts/{spacecraftId}:
    parameters:
      - name: spacecraftId
        description: The unique identifier of the spacecraft
        in: path
        required: true
        type: string
    get:
      summary: Read a spacecraft
      responses:
        '200':
          description: The spacecraft corresponding to the provided `spacecraftId`
          schema:
            $ref: './New.yaml#/definitions/Spacecraft'
        404:
          description: No spacecraft found for the provided `spacecraftId`
          schema:
            $ref: './New.yaml#/definitions/Error'
        500:
          description: Unexpected error
          schema:
            $ref: './New.yaml#/definitions/Error'
securityDefinitions:
  ApiKey:
    type: apiKey
    in: header
    name: X-Api-Key
security:
  - ApiKey: []